<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Puzzle Prototype</title>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Cabin:wght@400;600;700&family=Bubblegum+Sans&display=swap" rel="stylesheet">
    
    @if ($gallery->dificulty == 'hard')
    <link rel="stylesheet" href="{{ asset('main/puzzle.css') }}">
    @elseif ($gallery->dificulty == 'medium')
    <link rel="stylesheet" href="{{ asset('main/3x3.css') }}">
    @else
    <link rel="stylesheet" href="{{ asset('main/2x2.css') }}">
    @endif
</head>

<body>
    <div class="container">
        <!-- Updated Header Section - matching first example structure -->
        <div class="game-info">
            <div class="game-info-item round-info">
                BABAK: <span class="round" id="round">1</span>
            </div>
            <div class="game-info-item timer-info">
                WAKTU: <span class="timer" id="time">00:00</span>
            </div>
            <div class="game-info-item score-info">
                SCORE: <span class="score" id="score">0</span>
            </div>
        </div>
        
        <!-- Game Content Section -->
        <div class="game-content">
            <div class="drop-area">
                <div class="puzzle-grid" id="board">
                    <!-- Background hint layer -->
                    <div class="background-hint"></div>
                    <!-- Drop slots container -->
                    <div class="drop-slots-container">
                        <!-- Puzzle slots will be generated by JavaScript -->
                    </div>
                </div>
            </div>
            
            <div class="pieces-area">
                <div class="pieces-grid" id="pieces">
                    <!-- Puzzle pieces will be generated by JavaScript -->
                </div>
            </div>
        </div>
    </div>

    <!-- Modals -->
    <div id="loseMatchModal" class="modal">
        <div class="modal-content lose-match-modal">
            <button onclick="redirectToHome()"><span class="close" onclick="gameLogic.closeModal()">&times;</span></button>
            <h2 class="modal-title">GAME OVER</h2>
            <div class="game-over-icon">😵‍💫</div>
            <p class="lose-text">Jangan Menyerah, Explorator!</p>
            <p class="retry-text">
                Kembali ke   
                <button class="main-menu-btn" onclick="gameLogic.resetGame(); redirectToHome()">
                    <span class="btn-icon">🔄</span>
                    Main Menu
                </button> untuk Mencoba Tantangan Lainnya
            </p>
        </div>
    </div>

    <!-- Win Match Modal -->
    <div id="winMatchModal" class="modal">
        <div class="modal-content winner-modal">
            <button onclick="redirectToGallery()"><span class="close" onclick="gameLogic.closeModal()">&times;</span></button>
            <h2 class="modal-title">MENANG!</h2>
            <div class="trophy-display">
                <div class="trophy-icon">🏆</div>
                <div class="trophy-glow"></div>
            </div>
            <p class="winner-text">
                Kamu Memenangkan Tantangan!<br>
                <button class="reward-btn" onclick="redirectToGallery()">
                    <span class="btn-icon">⭐</span>
                    Ambil Hadiah
                </button>
            </p>
        </div>
    </div>

    <div id="loseRound2Modal" class="modal">
        <div class="modal-content lose-modal">
            <span class="close" onclick="gameLogic.closeModal()">&times;</span>
            <h2 class="modal-title">GAGAL!</h2>
            <div class="progress-indicators">
                <div class="indicator win">1</div>
                <div class="indicator lose">2</div>
                <div class="indicator treasure">🏆</div>
            </div>
            <p class="progress-text">Jangan Sia-siakan Kesempatan Terakhir!</p>
            <p class="countdown-text">Babak Final dimulai dalam <span id="countdown4">5</span> detik</p>
        </div>
    </div>

    <!-- Win Round 2 Modal -->
    <div id="winRound2Modal" class="modal">
        <div class="modal-content win-modal">
            <span class="close" onclick="gameLogic.closeModal()">&times;</span>
            <h2 class="modal-title">BERHASIL!</h2>
            <div class="progress-indicators">
                <div class="indicator lose">1</div>
                <div class="indicator win">2</div>
                <div class="indicator treasure">🏆</div>
            </div>
            <p class="progress-text">SELANGKAH LAGI UNTUK MENANG!</p>
            <p class="countdown-text">Babak Final dimulai dalam <span id="countdown3">5</span> detik</p>
        </div>
    </div>

    <!-- Lose Round 1 Modal -->
    <div id="loseRound1Modal" class="modal">
        <div class="modal-content lose-modal">
            <span class="close" onclick="gameLogic.closeModal()">&times;</span>
            <h2 class="modal-title">GAGAL!</h2>
            <div class="progress-indicators">
                <div class="indicator lose">1</div>
                <div class="indicator neutral">2</div>
                <div class="indicator treasure">🏆</div>
            </div>
            <p class="progress-text">Jangan Menyerah! Masih ada Kesempatan!</p>
            <p class="countdown-text">Round 2 starts in <span id="countdown2">5</span> detik</p>
        </div>
    </div>

    <!-- Win Round 1 Modal -->
    <div id="winRound1Modal" class="modal">
        <div class="modal-content win-modal">
            <span class="close" onclick="gameLogic.closeModal()">&times;</span>
            <h2 class="modal-title">BERHASIL!</h2>
            <div class="progress-indicators">
                <div class="indicator win">1</div>
                <div class="indicator neutral">2</div>
                <div class="indicator treasure">🏆</div>
            </div>
            <p class="progress-text">SELANGKAH LAGI UNTUK MENANG!</p>
            <p class="countdown-text">Babak 2 dimulai dalam <span id="countdown1">5</span> detik</p>
        </div>
    </div>

    <footer>
        <script>
            function redirectToGallery() {
                const galleryUrl = "{{ route('galleries.index', ['id' => $player_id]) }}";
                location.replace(galleryUrl); 
            }

            function redirectToHome() {
                const HomeUrl = "{{ route('room.index') }}";
                location.replace(HomeUrl); 
            }
        </script>
        <script>
            window.history.pushState(null, null, window.location.href);
            window.onpopstate = function () {
                window.history.pushState(null, null, window.location.href);
                alert("Tombol back dinonaktifkan selama permainan.");
            };
        </script>
        <script>
            document.addEventListener("keydown", function (e) {
                if ((e.key === "F5") || (e.ctrlKey && e.key === "r")) {
                e.preventDefault();
                alert("Refresh dinonaktifkan selama permainan.");
                }
            });
        </script>
        <script>
            window.onbeforeunload = function () {
                return "Permainan akan ter-reset. Apakah Anda yakin ingin meninggalkan halaman?";
            };
        </script>
        <script>
            const playerId = "{{ $player_id }}";
            const roomId = "{{ $room_id }}";
        </script>
        <script src="{{ asset('main/salsa20.js') }}"></script>
        @if ($gallery->dificulty == 'hard')
        <script src="{{ asset('main/game.js') }}"></script>
        @elseif ($gallery->dificulty == 'medium')
        <script src="{{ asset('main/3x3.js') }}"></script>
        @else
        <script src="{{ asset('main/2x2.js') }}"></script>
        @endif
    </footer>
</body>
</html>